name: Publish to my github.io

on:
  create:
    tags:
      - v*

jobs:
  github-io:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - name: Installing project dependencies
      - run: npm install
      - name: Building the project
      - run: npm run build
      - name: GitHub Pages action
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
