name: Publish to my github.io

on:
  push:
    tags:
      - v*

jobs:
  github-io:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_tag_name.outputs.VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run build
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
